%%{init: {'theme': 'neutral', 'themeVariables': { 'fontSize': '17px'}}}%%
sequenceDiagram
  participant W as Wallet Instance
  participant T as Credential catalogue + LoTE / TL
  participant I as PID / Attestation Provider
  W->>T: Credential Discovery: LoTE + catalogue + rulebook
  W->>T: Access CA + issuer anchors
  W->>I: OpenID4VCI
  I->>W: credential
  W->>W: Credential Verification<br>signature + data schema + revocation

